### ISSUE TITLE
No assistant UI

### ISSUE THREAD

**Issue by ajithkumar-natarajan** [ayush5harma/PixelFeatureDrops#1]
The module doesn't seem to work in Poco F1 running Pixel Experience 10.

**Comment by ayush5harma** [comment]
It works on pixel experience on any device.Please explain the issue.

**Comment by ayush5harma** [comment]
NgaResources is required for downloading the required data and was preinstalled in PE but is not there in recent builds causing issue downloading additional assistant update.
You can install below apk to fix your issue :
https://drive.google.com/file/d/1fTymlp9KaeTinK2D_UqAJUmaGwexeEz-/view

**Comment by ajithkumar-natarajan** [comment]
I installed NgaResources and the June release of P4XLProps on my Poco F1 running PE 10 (June security patch). Following are the results:

1. After reboot when I fired up Google Assistant it did prompt me that there needs to be an additional download (and I was excited that it is going to work finally) but it didn't. **Now I am unable to launch the Google assistant at all.** I only get the colors at the bottom if I swipe up from the corner but there is not Google assistant!
2. I am not able to check if ARCore is installed.
3. Ramping ringer: I believe that it was already there in PE.
4. Live Caption: PE already has it.
5. Pokemon go live wallpaper (Shown in Styles and Wallpapers): Does not show up in the wallpapers section.
6. UI overhaul for core google and some other apps.(enables by itself): Could not check.
7. Call Screening in countries where it is rolled out.(enables by itself): Does not work in the US.
8. AR Mode in google maps in countries where it's available.(enables by itself): Works in vanilla PE.
9. Google Photos portrait filter to add bookeh effect on any photo with faces taken as normal before.(enables by itself): I do not think it is working. But I may be wrong.
10. Google Duo portrait mode and autoframing during video calls.(enables by itself): Will update if I verify if it works.
11. 3D touch mimics on pixel launcher: Does not work.
12. Messages RCS (via Google messages app): It is no longer Pixel exclusive.
13. Rules in settings that help automate changes (Settings->System): PE supports it already.

**Comment by ayush5harma** [comment]
1. Speak to it and check. Aren't you getting text pop ups like in the attached screenshots below?
2. One can always install ARCore in high end devices like poco , low end devices  are benefitted here.
3. It's not.
4. Yes PE and Havoc has it . Derpfest,Paranoid android etc. doesn't.
5. Install pokemon wavehello from playstore :
https://play.google.com/store/apps/details?id=com.google.android.pokemonwavehello&hl=en_IN
and open styles and wallpaper from home screen and check under come alive section will show an option to download pokemon live wallpaper.
6. These are things like gboard streching itself to the navbar rather than leaving black strip in the pill area, and other UI changes gapps adopt in pixel series. 
7. Didn't the option appear in Dialer settings?
9. Use some gcam to take portrait photo and open it in photos app in the edit section there comes third option of blur which can be used to adjust the blur effect.Other photos taken as normal via gcam with faces can be converted to portrait using the same.
10. Install google Duo, make video call and options of autoframing and portrait appears in the bottom sheet.
11. I myself couldn't realise this ,will strike it as well from readme though the page at google says Long press improvements will roll out to Pixel 4 globally so it might come in future pixel drop but yes for now there's nothing.
12. Lol true.
13. For Rom which don't.
![photo_2020-06-18_11-50-55](https://user-images.githubusercontent.com/47772616/84985463-64878f00-b15a-11ea-8648-61a33cee1318.jpg)
Taken on PE plus June build device sakura.

**Comment by Viraj8456** [comment]
Google assistant 2.0 listens like a ghost.. But replies normally. I can surely say that it's a new assistant because of its speed and continued conversation...
Device and ROM: Potter, PE+ 10.

**Comment by ajithkumar-natarajan** [comment]
I have removed the module for now, will test over the weekend and update.

**Comment by ajithkumar-natarajan** [comment]
I reinstalled the module a couple of days ago. I also installed NgaResources. Following are my observations:

- The module could not be installed via Magisk. Once the module was installed and I rebooted, if I go to the Magisk modules section, I could not find the module. So I ended up copying the files into /data/adb/module. Now it shows up in Magisk modules section.

- I was mainly focused on the new assistant UI. It did not appear even after clear Google app's data and I had dropped my hopes. Suddenly today when I popped the Google assistant, there was a prompt for an update. Now there is no assistant UI. I see colors on the bottom of my screen when I swipe from the corner and the white lines on the edges when I use the 'Hey Google' hotword but there is no UI! It responds to my queries but there is no voice output at times. For example, 'what is on my calendar' shows up the items in my calendar but it does not read them out. I followed the steps mentioned [here](https://github.com/ayush5harma/P4XLProps/issues/2#issuecomment-671019450). My Google Play system is updated to September 2020 but I do not see any assistant UI now!

**Device**: Beryllium (Poco F1), Rom: Pixel Experience Plus Oct 2020 patch.

**Comment by suman-droid** [comment]
I have installed pixel experience in redmi note 7 pro. There is no Pokemon Wallpaper showing in coming alive section.. I updated all the app and also installed Pokemon wave from Google PlayStore  still there is no Pokemon Wallpaper.. Please someone help me.
