### ISSUE TITLE
Android 10, Security Patch: 05 november 2020

### ISSUE THREAD

**Issue by FraSharp** [ayush5harma/PixelFeatureDrops#17]
i'm on Android 10, with "5 november 2020" security patch, custom rom: Resurrection Remix OS (gsi arm64 AB)

i flashed the latest prop (P4XLProps-November) but my phone didn't boot.
when i flashed P4XLProps-August (that is the latest prop on android 10) my phone did not pass safetynet check

my phone: j6lte (SM-J600FN)

**Comment by ayush5harma** [comment]
- With P4XLProps-November the phone didn't boot because of invalid sdk presented by the prop as your device is running android 10 while the prop flag  _ro.build.version.sdk=30_  presents android 11. The prop is meant to spoof using the latest fingerprint from pixel 4 XL which is  on android 11. Android 11  and Android 10 version of these props have different signatures .If you still want to use android 11 pixel 4XL prop on android 10 you can comment out _ro.build.version.sdk=30_ line from system.prop file present in _/data/adb/modules/P4XLProps_ using some root based file manager or recovery.  
 Attached below is the module with the same modification flashing which  will allow you boot  and spoof your device as Pixel4XL but it won't help in enabling pixel feature drops.
[P4XLProps.zip](https://github.com/ayush5harma/P4XLProps/files/5571782/P4XLProps.zip)

- P4XLProps-August caused CTS failure because of mismatch with system security patch as mentioned in the readme.

**Comment by FraSharp** [comment]
ok thanks.
