### ISSUE TITLE
Support for adaptive charging on Poco F1?

### ISSUE THREAD

**Issue by iraniroahn** [ayush5harma/PixelFeatureDrops#24]
Does adaptive charging work on poco f1 (beryllium) or is it just exclusive to Pixel Devices?

**Comment by Viraj8456** [comment]
Maybe it's exclusive, it's not even working on Potter... I'm using PE11 beta. Maybe it works on Jan module... I'm on Dec.. 
But as far as I know, adaptive charging was introduced in Dec...

**Comment by ayush5harma** [comment]
> Does adaptive charging work on poco f1 (beryllium) or is it just exclusive to Pixel Devices?



> Maybe it's exclusive, it's not even working on Potter... I'm using PE11 beta. Maybe it works on Jan module... I'm on Dec..
> But as far as I know, adaptive charging was introduced in Dec...

The feature drop came in December on pixel devices but didn't work with the module installed on custom ROMs because of missing adaptivecharging.xml file which was added later to the module in January.

As of today the configurations are in both the Jan and Dec flashable zips found under release required for adaptive charging to kick in.

However adaptive charging itself is wonky - https://www.xda-developers.com/google-pixel-adaptive-charging-details/  
```
 According to a Google support document, via 9to5Google, you must have an active alarm
 set sometime between 5 – 10 a.m. in order for the feature to work. In addition, you must
 also put your phone on a charger after 9 p.m. Otherwise, Adaptive Charging won’t kick in
 and your device will charge normally.
```
