### ISSUE TITLE
No assistant 2.0 on CherishOs (Has pixel ui)

### ISSUE THREAD

**Issue by davigamer987** [ayush5harma/PixelFeatureDrops#40]
Assistant 2.0 wont work on cherishOs i already tried GSAprefs Fix but it didn't work

**Comment by ayush5harma** [comment]
I'll try this one today

**Comment by davigamer987** [comment]
Actually it doesn't work at all now, I even tried re installing cherishos

**Comment by ayush5harma** [comment]
> Actually it doesn't work at all now, I even tried re installing cherishos

as in ? Okay I'll try myself on cherish os 2.5 on realme 6

**Comment by davigamer987** [comment]
Shows a white border and won't open

**Comment by ayush5harma** [comment]
Ok got it no UI was due to customised pixel launcher that is shipped with cherishOS (This one provides double tap to sleep functionality).

Installing stock pixel launcher from pixel 5 solved the no UI issue.
attaching Pixel Launcher magisk module here :
[Pixel Launcher R v3.1.2.zip](https://github.com/ayush5harma/PixelFeatureDrops/files/6488822/Pixel.Launcher.R.v3.1.2.zip)

For glow you'll need the navbar variant of this module 
https://forum.xda-developers.com/t/magisk-pixel-launcher-for-android-11.4213619/

After flashing you too can update the pixel launcher to latest version from here - https://www.apkmirror.com/apk/google-inc/pixel-launcher/pixel-launcher-11-release/  
From June another variant of module will be added  for convenience.

**Comment by davigamer987** [comment]
By navbar variant you mean the one with navbar stuff or the one without navbar stuff?
