### ISSUE TITLE
None of the features are working!

### ISSUE THREAD

**Issue by Aarekaz** [ayush5harma/PixelFeatureDrops#41]
![Screenshot_20210514-082441_Google](https://user-images.githubusercontent.com/36888347/118213533-df057f80-b48d-11eb-87d5-82d348b4577d.png)
ROM Lineage OS 18.1
Gapps- mind the gap gapps
One Plus 5( but about device shows its Pixel 4)

I installed it and none of the features seem to work. Using latest Magisk, Sequrity version May 5
Smart compose is not showing up in google messages, google assistant is not opening, and more.

The assistant UI is like that.

**Comment by ayush5harma** [comment]
hmm.

- ![image](https://user-images.githubusercontent.com/47772616/118373130-d8cceb80-b5d2-11eb-88e8-40164fbc733a.png)
What’s the difference between AOSP based ROMs & Lineage based ROMs?
https://customroms.net/faq/aosp-vs-lineage-base/

- Tapping on About Phone and then Model  from settings shows Pixel 5 and there are nothing related to a pixel 4 in the build prop in all three variants available from release.

- Smart Compose is offered by Device Personalisation Services which is tightly coupled with google apps and services whereas lineage project since it's inception was made to be something free from Google apps and services.

**Comment by Aarekaz** [comment]
I didn't knew LOS was not a AOSP rom. My bad. Closing this issue.
