### ISSUE TITLE
Assistant does not wok on cherishOS (using Pixel Launcher port from Pixel 5)

### ISSUE THREAD

**Issue by davigamer987** [ayush5harma/PixelFeatureDrops#43]
Assistant does not work even with the pixel 5 launcher port. April security patch

Video of issue: https://streamable.com/5eshmo

**Comment by davigamer987** [comment]
When i disable the pixel props module it goes back to normal and assistant 2.0 opens, but if i enable it breaks assistant again :(

**Comment by ayush5harma** [comment]
> Assistant does not work even with the pixel 5 launcher port. April security patch
> 
> Video of issue: https://streamable.com/5eshmo

okay that didn't open i think you can attach mp4 in issues but okay let me try with vpn

**Comment by davigamer987** [comment]
https://user-images.githubusercontent.com/68574209/118525699-7cbab200-b70d-11eb-9975-ce08003e7757.mp4

**Comment by ayush5harma** [comment]
![image](https://user-images.githubusercontent.com/47772616/118524612-f7122300-b75b-11eb-81a0-553f8e4ed0e4.png)
Your GA 2.0 overlay is working fine only glow is missing. In the last issue did you use the pixel launcher module with navbar stuff?



![image](https://user-images.githubusercontent.com/47772616/118524512-dcd84500-b75b-11eb-87ad-fec1d99ae81a.png)
Since google app crashed when you triggered for assistant. I would suggest cleaning it's data.

In nutshell   

For glow to work 

- Use these variants - Pixel Launcher R v3.1 or v3.1.1  from here - https://forum.xda-developers.com/t/magisk-pixel-launcher-for-android-11.4213619/

- Also once this get's installed update the pixel launcher to latest release from here - https://www.apkmirror.com/apk/google-inc/pixel-launcher/pixel-launcher-11-release/

That's what i also had to do on my cherish OS 2.5 for realme 6

**Comment by davigamer987** [comment]
yes i downloaded the latest pixel launcher apk and i have the variant with all the navbar things (version 3.1), i tried clearing data, re-installing, if i remove the module it starts working again with glow an everything, something that the module does is breaking it (btw im on cherishOs 2.4 ) Sometimes a few seconds after i have opened the assistant with broken overlay the normal screen appears but its bugged and i cant talk

**Comment by davigamer987** [comment]
https://streamable.com/k9gayl This video i show that it sometimes opens but its bugged

**Comment by davigamer987** [comment]
update: i kinda fixed it, i used Weiju to change the google app device fingerprint to a random one and it worked, its ga 1.0 tho, still better than no ga at all tho, so basically it only has problems with ga 2.0 but that dosent explain why disabling the module makes it work

**Comment by davigamer987** [comment]
update 2.0: one time i got the module and ga 2.0 working but after a few seconds it reverted back to ga 1.0, very weird

**Comment by davigamer987** [comment]
https://streamable.com/iafivn

**Comment by davigamer987** [comment]
https://streamable.com/eawpw8 reverts back to ga 1 in a few seconds (i had Weiju enabled) 

I hope all the info i gathered is enough for you to possibly understand the issue better :)

**Comment by davigamer987** [comment]
and ok google is also broken

**Comment by ayush5harma** [comment]
> https://streamable.com/k9gayl This video i show that it sometimes opens but its bugged

First things first-  Your Cherish OS doesn't seem to me to be gapps build from seeing the videos you linked.
And also
Google never asks for permission like this, its a system-priv app in gapps build 
![image](https://user-images.githubusercontent.com/47772616/118631344-04c3b900-b7ed-11eb-9b10-4154bcccbf55.png)

So if you flashed vanilla and used  some package of gapps after that. Then all your weirdness is because of it.

**Comment by ayush5harma** [comment]
> and ok google is also broken

remove the module and check google hotword detection if it works or not.Because if it is not even working without the module it's the ROM issue.

**Comment by ayush5harma** [comment]
Which device is yours?

**Comment by davigamer987** [comment]
Im using an s20 fe 5g with braialindo’s offcial gsi, includes gapps but its a very minimal gapps with only play store and some other stuff by default, i had to install google app from play store

**Comment by ayush5harma** [comment]
Out of scope...
