### ISSUE TITLE
Redmi K20/K20Pro/Mi9T Camera Pop-ups

### ISSUE THREAD

**Issue by macfusbluer** [ayush5harma/PixelFeatureDrops#46]
Hi,

I've installed May Pixel Features on a Xiaomi Mi 9T. After installing Magisk module I did a reboot to let the module start. During boot animation camera pop-ups and keeps that way. I had to use ROM's camera calibration option under Settings to make it hide again.

I'm using now Pixelish ROM, latest May update. It also happened using Picsel Inexperience and Pixel Experience.

Regards!

**Comment by rgvxsthi** [comment]
Hi there,

@Aryannn999 on Telegram has managed to integrate the fixes required for Mi 9T/9T Pro camera pop-ups and buggy AUX lenses with the latest PixelFeatureDrops update. A link to the same can be found here - [https://t.me/randomfilezz/298)](https://t.me/randomfilezz/298)

I will try to get a source from him regarding the patches so that those can be implemented here as well (if there are no overlaps with other features)
